# See https://docs.npmjs.com/trusted-publishers
# See https://pnpm.io/continuous-integration

name: Publish Package

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      - run: pnpm stage publish --no-git-checks --access public
